// Code generated by gop (Go+); DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/qiniu/x/errors"
	"github.com/xushiwei/gsh"
	"strconv"
	"strings"
)

const _ = true

type file struct {
	name  string
	fsize int
}
type example struct {
	gsh.App
}
//line example.gsh:6
func (this *example) MainEntry() {
//line example.gsh:6:1
	func() {
//line example.gsh:6:1
		var _gop_err error
//line example.gsh:6:1
		_gop_err = this.Gop_Exec("mkdir", "testgsh")
//line example.gsh:6:1
		if _gop_err != nil {
//line example.gsh:6:1
			_gop_err = errors.NewFrame(_gop_err, "mkdir \"testgsh\"", "example.gsh", 6, "main.MainEntry")
//line example.gsh:6:1
			panic(_gop_err)
		}
//line example.gsh:6:1
		return
	}()
//line example.gsh:8:1
	this.Gop_Exec("mkdir", "testgsh2")
//line example.gsh:9:1
	func() {
//line example.gsh:9:1
		var _gop_err error
//line example.gsh:9:1
		_gop_err = this.LastErr()
//line example.gsh:9:1
		if _gop_err != nil {
//line example.gsh:9:1
			_gop_err = errors.NewFrame(_gop_err, "lastErr", "example.gsh", 9, "main.MainEntry")
//line example.gsh:9:1
			panic(_gop_err)
		}
//line example.gsh:9:1
		return
	}()
//line example.gsh:11:1
	this.Gop_Exec("mkdir", "testgsh3")
//line example.gsh:12:1
	if this.LastErr() != nil {
//line example.gsh:13:1
		panic(this.LastErr())
	}
//line example.gsh:16:1
	this.Capout(func() {
//line example.gsh:16:1
		this.Gop_Exec("ls")
	})
//line example.gsh:17:1
	fmt.Println(strings.Fields(this.Output()))
//line example.gsh:19:1
	this.Capout(func() {
//line example.gsh:19:1
		this.Gop_Exec("ls", "-l")
	})
//line example.gsh:20:1
	files := func() (_gop_ret []file) {
		for
//line example.gsh:20:1
		_, e := range strings.Split(this.Output(), "\n") {
//line example.gsh:20:1
			if
//line example.gsh:20:1
			flds := strings.Fields(e); len(flds) > 2 {
//line example.gsh:20:1
				_gop_ret = append(_gop_ret, file{flds[8], func() (_gop_ret int) {
//line example.gsh:20:1
					var _gop_err error
//line example.gsh:20:1
					_gop_ret, _gop_err = strconv.Atoi(flds[4])
//line example.gsh:20:1
					if _gop_err != nil {
//line example.gsh:20:1
						_gop_err = errors.NewFrame(_gop_err, "flds[4].int", "example.gsh", 20, "main.MainEntry")
//line example.gsh:20:1
						panic(_gop_err)
					}
//line example.gsh:20:1
					return
				}()})
			}
		}
//line example.gsh:20:1
		return
	}()
//line example.gsh:21:1
	fmt.Println(files)
//line example.gsh:23:1
	this.Gop_Exec("rmdir", "testgsh", "testgsh2", "testgsh3")
}
func main() {
	gsh.Gopt_App_Main(new(example))
}
